name: 'Build and publish package'

on:
  push:
    branches:
      - develop
      - main
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
    paths-ignore:
      - 'README.md'
      - 'docs/*'
      - 'scripts/*'
      - '.vscode/*'
  pull_request:

permissions:
  checks: write
  contents: write
  pull-requests: write
  actions: read
  packages: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  NUGET_CERT_REVOCATION_MODE: offline
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:

  net-build:
    name: .NET build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore NuGet packages
      run: dotnet restore --verbosity minimal

    - name: Test analyzer solution
      run: dotnet test Karls.Analyzers.sln --configuration Release

    - name: Setup timestamp
      if: github.ref != 'refs/heads/main'
      id: timestamp
      run: echo "::set-output name=value::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Pack analyzer project
      run: dotnet pack src/Karls.Analyzers/Karls.Analyzers.csproj --configuration Release --output ./artifacts --version-suffix ${{ steps.timestamp.outputs.value }}

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: artifacts/*.nupkg

  publish-internal:
    name: NuGet Publish (Github Package Registry)
    needs: net-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          global.json
        sparse-checkout-cone-mode: false

    - name: Download artiifacts
      uses: actions/download-artifact@v4
      with:
        name: packages
        path: ./artifacts/

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Setup nuget registry
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/karl-sjogren/index.json"

    - name: Publish to nuget registry
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

  publish:
    name: NuGet Publish (NuGet.org)
    needs: net-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          global.json
        sparse-checkout-cone-mode: false

    - name: Download artiifacts
      uses: actions/download-artifact@v4
      with:
        name: packages
        path: ./artifacts/

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Publish package to NuGet.org
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: dotnet nuget push artifacts/*.nupkg --api-key $NUGET_KEY --source https://api.nuget.org/v3/index.json
      working-directory: ./
